name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_empire:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'empires-puzzles-api' }}
      run: |
        cd ./empirespuzzlesapi
        docker login --username=mt15-0094@unphu.edu.do -password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
